sudo: required
language: python
python:
  - "3.7"
dist: trusty
addons:
  chrome: stable
before_install:
  - pip install selenium
  - wget https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install -r requirements.txt
script:
  - pytest
